### ISSUE TITLE
bidscoiner function leaves out every sequence

### ISSUE THREAD

**Issue by rbonicel** [Donders-Institute/bidscoin#221]
Hi Marcel

**Describe the bug**
I properly sorted all data using `dicomsort` (thanks again) and ran the `bidseditor`. I edited every entry in the bidseditor (either excluding them or giving them the expected name. I validated my bidsmap (all good), saved it to the ref location and closed the GUI. When running the `bidscoiner` function, every sequence is left out for every subject and nothing is converted to bids format 

**Expected behavior**
Given my `bidsmap.yaml `(which I can provide if needed), I expect some sequences to be converted to `.nii` and bids format

**Screenshots**
Some of the validated items : 
![Screenshot from 2024-01-25 16-33-28](https://github.com/Donders-Institute/bidscoin/assets/48990813/7b027832-812f-4c6c-8a8e-1b4cbe8c62ac)

Some of the excluded items : 
![Screenshot from 2024-01-25 16-34-48](https://github.com/Donders-Institute/bidscoin/assets/48990813/88d341ab-6e90-44e2-bed6-1c6c5516b408)

**Software version**
 - BIDScoin 4.3.0
 - OS Linux

**Additional context**
I made a test on one sub/ses folder. 
Here is the part of the `bidsmap.yaml` where a file of the `T1w` needed renaming. This part is inside the `anat:       # ----------------------- All anatomical runs --------------------` subpart of the bidsmap. 
![Screenshot from 2024-01-25 16-59-25](https://github.com/Donders-Institute/bidscoin/assets/48990813/4e679161-eb41-4963-8b70-7197fe3b5fbb)

And here is the result of the run of the `bidscoiner` : 
![Screenshot from 2024-01-25 16-42-32](https://github.com/Donders-Institute/bidscoin/assets/48990813/97540a1e-5cdd-4de0-b1e7-df768b215276)

I expected at least the `1101-WIP T1_3DTFE_ADNI_ISO10` to be converted, as it is the one shown in the bidsmap, but this is not the case. 
 
I looked into issue https://github.com/Donders-Institute/bidscoin/issues/40#issue-466795680 because the last item in the bidseditor was an `exclude` data, but I'm not sure it relates. 

I can provide the data from the subject shown, and my bidsmap for a test run if needed. 

Thanks

**Comment by marcelzwiers** [comment]
Have you manually editted the bidsmap after running the bidseditor?

**Comment by rbonicel** [comment]
> Have you manually edited the bidsmap after running the bidseditor?

No, I didn't touch the bidsmap outside of the editor. 
Is there an order to perform steps on the bidsmap ? `Validate` then `save`, then close the editor ? 

I just happen to do a test on one single exam from scratch :
- `dicomsort` went ok
- `bidsmapper` went ok
- the last item to edit on the bidsmap in the bidseditor happened to be a file to keep 
- `bidscoin` went ok

In the end, does this "last item in the bidseditor being an exclude" have something to do with my issue ?
Could I create a "false" last item to keep ?

**Comment by rbonicel** [comment]
If I run again `bidsmapper /raw /bids` on my complete database with the bidsmap I saved for this database, when the `bidseditor` opens, every single item is marked as `exclude` data, which would explain the behaviour of the `bidscoin` command after that.

I can send you my bidsmap via sharepoint if you wish to have a look at it.

**Comment by marcelzwiers** [comment]
Strange, yes, I'd be happy to see that bidsmap!

**Comment by rbonicel** [comment]
I uploaded my bidsmap to the SURFdrive. Please let me know if you need any additional document to investigate.

**Comment by marcelzwiers** [comment]
Thanks, I received:
```
bidsmap.yaml
bidsmap (2).yaml
bidsmap_bkp.yaml
bidsmap_working.yaml
```
Which is which?

**Comment by rbonicel** [comment]
I answered this in email form, sorry. I'll copy it here : 

The "bidsmap.yaml" (that I mistakenly uploaded twice) is the most up-to-date one. It includes the two exams I sent you, properly sorted.  The bidsmap_bkp.yaml is the one without those two exams.
I also uploaded a "bidsmap_working.yaml" file to the sharepoint. This bidsmap relates to the single-subject test I mentioned in the github issue where everything went fine from start to finish.

**Comment by marcelzwiers** [comment]
> If I run again bidsmapper /raw /bids

Did you, by any chance use the `-f` option? Because that discards any existing bidsmap and starts from scratch...

**Comment by rbonicel** [comment]
> > If I run again bidsmapper /raw /bids
> 
> Did you, by any chance use the `-f` option? Because that discards any existing bidsmap and starts from scratch...

No, I specifically checked that this flag was not in the command, because I wanted to reload the bidsmap I created and control the renames I made. 
If this flag was included in the command (which it unfortunately was, for one on my test, which forced me to rename all the files a second time), it would give me a fresh run of the command. That is to say that in the `bidseditor`, I'd have a mix of `exclude`, `extra_data`, and even prenamed `anat`, `dwi` and so on. 

On this second run, use specifically to reload the created bidsmap, every single item is labeled as `exclude`.

**Comment by marcelzwiers** [comment]
Running bidsmapper again re-uses any existing bidsmap, and creates a new one if it can't find one. So re-running the bidsmapper certainly didn't change your datatypes and bidscoiner simply uses the bidsmap you give it. I suspect that you have been giving different names to your bidsmaps and when re-running the bidsmapper, you must have given a wrong (`-b`) bidsmap. Same is true for the bidscoiner, did you pass your (non-standard name) of the bidsmap you wanted to use?

**Comment by marcelzwiers** [comment]
I had another look at the code that searches for your bidsmap. It could be that when it couldn't find your bidsmap, it took the template bidsmap (which is better than nothing, right? ;-)). I will add some extra checks for this. Anyway, I still think your exclude issues are caused by passing a wrong/missing name of your bidsmap

**Comment by rbonicel** [comment]
I forced reinstall the bidscoiner with your latest commit.
The names I gave my bidsmaps in the sharepoint were just to tell them apart. When using the `bidsmapper` or `bidscoiner` functions, I always name them `bidsmap.yaml` which is the default name and store them in the default location given by the app, which is `<bids_folder>/code/bidscoin`. 

I tried running the `bidsmapper` again wth the default setting and then using the `-b` flag and pointing is especially to my bidsmap, using absolute path : `/home/robin/Documents/Database/PIP/no_modif_tag/bids_complete/code/bidscoin/bidsmap.yaml` Should I maybe use relative path ?

Did you happen to find anything of interest in my bidsmaps that could explain the problem ?

**Comment by rbonicel** [comment]
I do have a question, though, that could explain the behaviour. I'll try to rephrase it better in this issue.

I have to rename a file regarding a sequence I want to keep : 
`  - provenance: /home/robin/Documents/Database/PIP/no_modif_tag/raw_bids_complete/sub-99181100801109/ses-02/01-/1101-WIP T1_3DTFE_ADNI_ISO10/IM_0414`
Once renamed, it gets to the `anat` section of the bidsmap.

I then go onto a `PS_` file I don't want to keep. It's stored alone in a folder beginning by `000` as `SeriesNumber`
`  - provenance: /home/robin/Documents/Database/PIP/no_modif_tag/raw_bids_complete/sub-99181100853106/ses-01/01-/000-WIP T1_3DTFE_ADNI_ISO10/PS_0222`
Once renamed, it goes to the `exclude` section of the bidsmap. But it relates to he same sequence name, though `WIP T1_3DTFE_ADNI_ISO10` . Could this explain the behabiour ? One file kept but another excluded, both related to the same sequence ?
That shouldn't because as you told mz, if DICOM fields are different between sequences, it will consider them to be two different sequences. And indeed there is way less info in a `PS_` file than in a real image file.

The workaround I see is starting from the bidsmap and `/raw /bids` folders that work, and contain one single subject, nd adding one by one other subjects, running the bidsmapper each time and completing the existing working bidsmap.

**Comment by rbonicel** [comment]
> The workaround I see is starting from the bidsmap and /raw /bids folders that work, and contain one single subject, nd adding one by one other subjects, running the bidsmapper each time and completing the existing working bidsmap.

I did try that, but I encountered a parsing error because the files paths where incorrect (I copied the content of <bids_folder1> into <bids_folder2>. Obviously, it didn't work because the paths where relative to <bids_folder1>)
So I started a new database with only one subject and 2 sessions, and filled a bidsmap. 
What was different from this test https://github.com/Donders-Institute/bidscoin/issues/221#issuecomment-1910686986 is that the last few files to rename in the bidsmap were `exclude` files. I checked the path and name of the created bidsmap and reloaded it again. Without failing, the second run of `bidsmapper` gave me a bidseditor filled with `exclude` type data, including the ones I renamed. 

I'm really wondering if an `exclude` last item in the bidseditor (and of the created bdsmap) doesn't create this behaviour. 
To assert this, I'll fill in a new bidsmap with the same subject used in this test https://github.com/Donders-Institute/bidscoin/issues/221#issuecomment-1910686986, and purposely put the last item as `exclude`. I'll write the results by editing this comment.

**Comment by rbonicel** [comment]
I started printing out stuff in the code.
The `bidscoiner` function seems to behave as expected, when it gathers info from the bidsmap.yaml. That's the reading of the bidsmap.yaml that seems off.
i.e here we have the very first item in the `dwi` section : 
![Screenshot from 2024-01-29 16-54-27](https://github.com/Donders-Institute/bidscoin/assets/48990813/a85d0cbf-32f4-4d5e-8531-48ed28947d09)And 
And when I print out the `datasource.datatype` of the item, it's always considered as `exclude`, as if it were in the `exclude` section of the bidsmap : 
![Screenshot from 2024-01-29 16-56-20](https://github.com/Donders-Institute/bidscoin/assets/48990813/08573f0a-f6a6-4e4c-9c68-5e9641dc19e3)

According to the terminal, the path of the seected bidsmap.yaml file is right to me : `INFO | Reading: /home/robin/Documents/Database/PIP/no_modif_tag/bids_complete/code/bidscoin/bidsmap.yaml`
This is where I stored by info, that I can read using gedit, follow through the execution of the `bidscoiner` command. But it seems to consider every item to fall in the following condition : 
![Screenshot from 2024-01-29 17-01-38](https://github.com/Donders-Institute/bidscoin/assets/48990813/2a0763f6-4f8f-4b95-bbf4-82b8cd4452d3)

So it seems a little out of my depth here. I will print out more info from the code to up the the trail, if it helps.

**Comment by marcelzwiers** [comment]
If I run bidsmapper and bidscoiner on your data it all works fine. Perhaps you are using the bidsmap created with 4.2.1 with bidscoiner 4.3.0? What if you run bidscoiner 4.2.1?

**Comment by marcelzwiers** [comment]
Ah well, I don't think that it is, but it would still be interesting to know if bidscoiner 4.2.1 works normally. All your scans somehow match with run-items in the `exclude` section of your bidsmap...

**Comment by marcelzwiers** [comment]
To find which match is causing your issues, you can add this print statement to `bids.py`, line 1736:
```
            # Stop searching the bidsmap if we have a match
            if match:
                print(f"--- DEBUG ---: bidsmap match: {run['provenance']}")
                return run_, True
```

**Comment by rbonicel** [comment]
> If I run bidsmapper and bidscoiner on your data it all works fine. Perhaps you are using the bidsmap created with 4.2.1 with bidscoiner 4.3.0? What if you run bidscoiner 4.2.1?

That would explain something I noticed in the text box of the bidseditor : 
![Screenshot from 2024-01-30 09-30-32](https://github.com/Donders-Institute/bidscoin/assets/48990813/3002c7f5-8b52-4062-8105-c54ddf96dba5)
How do I force everything to run on 4.2.1 ? I still have both folders in the `~/.bidscoin` foldern for the two versions, after the force reinstall. 
However, I seem to recall that this behavior of the `bidscoiner` command was already present in 4.2.1 . 
But yes, I'm pretty sure my bidsmap was created using 4.2.1, and here I run it with 4.3.0

**Comment by rbonicel** [comment]
> Ah well, I don't think that it is, but it would still be interesting to know if bidscoiner 4.2.1 works normally. All your scans somehow match with run-items in the `exclude` section of your bidsmap...

The check of the items in the bidsmap seems fine and according to the `datatype` I choose to sort each file under. 
When it comes to coining, all `datatype` switch to `exclude` . Would it be because the `datatype` is empty, as shown in the screenshots, and therefore assimilated as an `exclude` file ?

**Comment by marcelzwiers** [comment]
You don't need to worry about the config directories. Each bidscoin version only looks into it's own folder. I don't think an empty datatype is the problem, but you ever know. If you install the latest version from github and in your terminal run: `export BIDSCOIN_DEBUG=TRUE`, then you will get some more info when running bidscoin commands

**Comment by rbonicel** [comment]
Ok, I printed out the `bidsmap match` you advised, and I found a surprise. If I focus on a supposed kept file, the same I listed in my screenshots, I get this : 
![Screenshot from 2024-01-30 09-46-16](https://github.com/Donders-Institute/bidscoin/assets/48990813/9be4c687-0433-4f81-8487-c23e320014ba)
It matches with another file in the bidsmap ! Interesting enough, this `IM_1116` file is the very last item in the `exclude` part of the bidsmap. Interestingly enough, this  `IM_1116` file is used as bidsmap match for other items I want to keep.

If I look at an item I don't want to keep : 
The match is made on the correct file, hence the correct behaviour. 

Another thing I suspected in a previous comment : I had to rename a `1101-WIP T1_3DTFE_ADNI_ISO10/IM_0414` I do want to keep, and also a `201-WIP T1_3DTFE_ADNI_ISO10/XX_0012` I don't want to keep, because it was the only file in sequence folder (because the sequence was launched but not acquired). But they refer to the same sequence, and the matching is done on the file I don't want to keep : 
 
![Screenshot from 2024-01-30 09-57-25](https://github.com/Donders-Institute/bidscoin/assets/48990813/149a83ec-4874-4146-b7ad-69601c408757)
So, in fact : when it relates to a sequence I want to keep, even if I don't want to keep said `XX_` file, I need to rename it as a kept file ?

I think we have a clearer view now, thanks to your print. Why does a file A get matched with a file B, when file A is in the bidsmap already ?

**Comment by marcelzwiers** [comment]
Renaming provenance doesn't do anything, except when you change the datatype in the bidseditor, then the editor uses the provenance path to go back to the original source and re-read the attributes needed for the new datatype

**Comment by marcelzwiers** [comment]
Bidscoin searches through datatypes from top to bottom and it stops as soon as a match is found

**Comment by marcelzwiers** [comment]
The order of the datatypes is:
```python
for datatype in ignoredatatypes + bidsdatatypes + unknowndatatypes:         # The ordered datatypes in which a matching run is searched for
```

**Comment by marcelzwiers** [comment]
So what I think is happening is that your exclude item is too broad (either because of the anonymisation or because you removed things like TE and TR from the bidsmap?), you should add information to make it more specific

**Comment by marcelzwiers** [comment]
A data source is matched on the attributes (and/or properties if you want), the provenance is the representative source of the attributes, but is not used

**Comment by rbonicel** [comment]
I could then create a new bidsmap using bidscoin 4.3.0 and running an all 4.3.0 pipeline ? Could this be useful ?
I figured the order of the datatypes, yes, but still don't know why the match is done on a completely different file in the `exclude` section, furthermore a file that has nothing in common with the sequences I want to keep

**Comment by marcelzwiers** [comment]
I would first delete the trouble causing `exclude` item from your bidsmap, then re-run the bidsmapper and see if this solves the issue

**Comment by marcelzwiers** [comment]
If it doesn't, then you need to find something in the DICOM header that is specific for this exclude item and add that DICOM field + value to the attribute list

**Comment by rbonicel** [comment]
> So what I think is happening is that your exclude item is too broad (either because of the anonymisation or because you removed things like TE and TR from the bidsmap?), you should add information to make it more specific

I did remove TE and TR from the bidsmap template, to go from 650 files to rename to 220 something. Maybe I ought to keep all the info and rename more files because of the way our protocol was set up and that our Philips files are a complete mess ?
I'll try to remove the item, if not, I start from scratch with 650 items, if that's what I have to do.

**Comment by marcelzwiers** [comment]
You should not have deleted all TE's and TR's from the bidsmap, only those that varies somewhere in a late decimal. E.g. when you have the same frmri scan, but the have TR of 2.00000301, 2.00000021, 1.999999998, etc. Other scans may still all have TR = 0.7000

**Comment by rbonicel** [comment]
I tried running 4.2.1, but the bidsmap was created with 4.3.0, so I have conflict of items when checking the bidsmap run-items.

Best course of action is start again from scratch (I still have old bidsmaps to recall how I sorted files) including TE and TR and rename everything thouroughly.
I could remove TE and TR on some specific sequences as you advise, not all.

**Comment by marcelzwiers** [comment]
It's probably something that Philips is doing, writing tiny corrections from the scan protocol into the header (I've also seen Siemens doing something like that). A work around is to add a regular expression to your study bidsmap, giving a range of TR's or TE's. But that's a bit of advanced usage, but here's an example for `filesize` (in the comment), but you can translate that for TE, TR or any other property or attribute:
```yaml
filesize:                   # File size, e.g. "2[4-6]\d MB" for matching files between 240-269 MB
```

**Comment by marcelzwiers** [comment]
`TE: "30\.00.*"` will match anything between >`30.00` and <`30.01`

**Comment by rbonicel** [comment]
Thanks, I'll try that.

I removed the last `exclude` item from the bidsmap. I have some correct matching now, and the coining/conversion completes. I've looked at the first few files on the list. But I also have some left out files that should be kept, and the matching is done on another random item of the `exclude` list. 
I could go on removing items from the exclude list, but I think running everything back with the TE/TR is the safer and cleaner bet, however long it might be.

**Comment by marcelzwiers** [comment]
So are both the TE and TR varying in some small decimal, or just the TE or TR? And if so, which is it?

**Comment by marcelzwiers** [comment]
Getting 223 back is fine, but you should have putted back the TR and TE in the template bidsmap before you re-ran the bidsmapper

**Comment by rbonicel** [comment]
> Getting 223 back is fine, but you should have putted back the TR and TE in the template bidsmap before you re-ran the bidsmapper

Yeah, I don't get why I had the same number of items with TE/TR back for exclude item. So, now, I'm currently filling  bidsmap for 650 items, to be as thorough as possible regarding our cohort. And I'll build up from here. 

I didn't expect our data to create such complex issues. At least for future exams, I won't have to worry about what the Philips anonymization procedure does, as I'll now exactly which tags will be kept/removed/modified

**Comment by marcelzwiers** [comment]
So is it both the TR and TE of all scan types? I find that unlikely, but at the same time I worry that the Siemens-based dccn template, which is the default, is causing issues for many more Philips users (I haven't heard any complaints so far)

**Comment by marcelzwiers** [comment]
Btw, I added this FAQ to explain what is happening:

https://bidscoin.readthedocs.io/en/latest/troubleshooting.html#my-bidsmap-list-is-much-longer-than-the-number-of-scan-types

**Comment by rbonicel** [comment]
The FAQ is a good idea. 
In the protocol in which we are included, we're the only Philips machine. Every other center has a Siemens, and sold me Bidscoiner as "super easy, super straightforward". I'm sure it works wonders on Siemens data, though. 
So I didn't have anyone to talk to regarding my problems, hence both issues. I expected to see some Philips center complaining in the issues, but I haven't found any. 
Would you consider creating bidsmap templates for the other manufacturers (Philips, GE, Canon) in the future, or that's not planned ?
I'd like to see how the Bidscoiner behaves with non anonymized data, with every tag available. Hopefully it will be simpler with the upcoming exams, but as you said, Philips may put some extra info in the DICOM header or eslewhere that would always cause this behavior, with the Siemens template bidsmap. 

Let's also see how Bidscoiner behaves with a complete and extensive bidsmap, maybe that will solve everything !

**Comment by marcelzwiers** [comment]
Sure, I'd be happy to add a template for Philips, but I myself don't have access to Philips data. So it makes it hard for me to develop such a template

**Comment by rbonicel** [comment]
> So is it both the TR and TE of all scan types? I find that unlikely, but at the same time I worry that the Siemens-based dccn template, which is the default, is causing issues for many more Philips users (I haven't heard any complaints so far)

I think that's mostly the TR that "duplicates" the files because it has countless digits after the comma, whereas TE only has 2. So I think the extensive bidsmap could help on the matching of the files for the `bidscoiner` step.

**Comment by rbonicel** [comment]
After hours, I finished the renaming of all the files in the `bidseditor`. I had to rename countless times the same sequences, because the TE/TR were slightly different between scans. 
Regarding the doubt I had about the `PS_` and `XX_` files that refer to sequences I want to keep, I did 3 bidsmaps :
- One with those `PS_` and `XX_` files labeled as `extra_data`
- One with those `PS_` and `XX_` files labeled as `exclude` data
- One with those `PS_` and `XX_` files properly renamed according to the sequence I want to keep.

All three gave the same result : every single sequence of the cohort is left out. 
The matching is as completely erratic as before, a random item of my `exclude` section in the bidsmap is selected to match a bunch of files I want to keep, and the files I want to exclude are mainly matched with themselves from the `exclude` section of the bidsmap.
As I have more files renamed, the `exclude` section of the bidsmap is bigger. I don't understand the matching, but I think the order of the datatypes (starting by the `exclude` section ) completely jeopardizes the matching for my data.
The selected `exclude` iem that comes forward often is the following one : 

![Screenshot from 2024-01-30 17-14-03](https://github.com/Donders-Institute/bidscoin/assets/48990813/cdbbe2bb-e2e1-4f90-bee7-330342788fe1)


It's fairly empty info-wise, so that's probably why it's taken as match for most files  

I could remove one by one the "false" `exclude` items taken as matches for files I want to keep, but I have no idea how these  `exclude` items will be handled by the bidscoiner.

I'm fairly tempted to give it up as it is and create a small "bids" dictionary in Python in order to rename my NIFTI files in bids form according to their filename (task/acquisition, direction, run and so on...).
I don't know what else to do. If you have further advice, please feel free to share.

Thanks for your help for both issues.

**Comment by marcelzwiers** [comment]
I'm sorry for your troubles, but it is very unambiguous that if everything is empty except `{Modality: MR}` that such an item will match with any DICOM file. The question is, how is it possible that all these attributes are empty? I thought for instance that ProtocolName was preserved?

**Comment by marcelzwiers** [comment]
Btw, that provenance path doesn't look like it was sorted by the latest dicomsort

**Comment by rbonicel** [comment]
> Think of it like this, every attribute is used to discriminate between scans, the more (non-empty) attributes you have, the more selective the matching will be. In the screenshot you select for one thing, namely, the imaging modality is MR

I thought that it was the other way around, given this weird matching. I thought the more empty fields you had, the more matching items you could get.

As for the file I showed in the screenshot above, it comes from the very first exam we acquired, and for some reason, it doesn't have the `SeriesDescription` nor the `ProtocolName`. In fact, I just checked, it doesn't have any of the tags listed as items in the bidsmap. So the bidsmap is correct in that aspect. The `dicomsort` sorted the exam according to `SeriesNumber`, one of the only tags available. The DICOM files have some tags, but none taken by the bidscoiner. 
I have two exams like this, maybe for those I should force write a `SeriesDescription` and `ProtocolName`. Would that be enough, I don't know. 
I will do that, then sort the whole thing again with the latest dicomsort. 
But the `dicomsort` gave me some trouble as well, that I didn't mention. The sorting sequences folder were not organized properly for some subjects, so I rearranged it manually. 
Should I keep the organization as it is, as the outpuut of the function ? FYI, for some exams, I had some sorted sequence folder at the root of the exam (which is ok) and some hidden inside the origin /DICOM folder. Maybe because the DICOMDIR is weirdly made, and the `dicomsort` simply followed it like it should.

**Comment by marcelzwiers** [comment]
> I thought that it was the other way around, given this weird matching. I thought the more empty fields you had, the more matching items you could get.

Think about it this. Suppose you want to make a list of the different kinds of people living on this planet (so that you can name them) and that you can ask each person any question. You will start by defining a few questions that you will ask everybody, and then, based on their answers you can make a list. For instance, if you only asked their gender, you would have ended up with three categories (male, female, non-binary or so). If you add a second question, you become more selective, getting better-defined categories, but your list of categories gets longer (e.g. if you add the question whether they had academic training, you get more categories: academic male, academic female, academic non-binary, non-academic male, etc)

The analogy of the Philips TR value is that you suddenly come across a group of people that do not give yes or no for an answer but say they had some academic training, or that they had two trainings, etc. That why you had your longlist of scan types in the bidseditor

> As for the file I showed in the screenshot above, it comes from the very first exam we acquired, and for some reason, it doesn't have the SeriesDescription nor the ProtocolName. In fact, I just checked, it doesn't have any of the tags listed as items in the bidsmap. So the bidsmap is correct in that aspect.

So this is again all due to heavy anonymization or is it some kind of special meta-file? 

> But the dicomsort gave me some trouble as well, that I didn't mention. The sorting sequences folder were not organized properly for some subjects, so I rearranged it manually.

As long as you put the dicomfiles from one series in one folder (so ./sub-#/ses-#/seriesfolder/dicomfiles) then it should work as expected. Anyhow, it seems sorting is not the root of the problem, it still is the anonymization

**Comment by marcelzwiers** [comment]
There is something I can do, which is taking the absence of a value as a value. It's a fundamental change and I need to think about it a bit more

**Comment by marcelzwiers** [comment]
>  it doesn't have the SeriesDescription nor the ProtocolName
Do you mean their values were empty or were the fields completely taken out of the header (which makes them invalid DICOM)

**Comment by rbonicel** [comment]
> > it doesn't have the SeriesDescription nor the ProtocolName
> 
> Do you mean their values were empty or were the fields completely taken out of the header (which makes them invalid DICOM)

The fields were not present in the DICOM (I use MRIConvert to read the tags, I have a bit of trouble making the difference between the header and the rest). But this file can still be open with pydicom, which makes it a valid DICOM file. Among the tags you use as your `attributes`, some were present but empty, some were absent from the file.

> There is something I can do, which is taking the absence of a value as a value. It's a fundamental change and I need to think about it a bit more

I've taken the option of writing some tags in the DICOM files for said subjects, to avoid you doing that, and to have files better suited for the bidscoiner. Only two tags, it's not much, but it could help discard this file as the "goto" file, among others. 
Just one question : why did you choose the order of the `datatypes` as it is, starting with the `exclude` files and not the bids files you want to keep ( `anat`, `dwi` and so on) ? I guess it works better this way, but with my cohort, it seems to induce the error. 

I'll tell you what filling/creating the tags does to the bidscoiner.

**Comment by marcelzwiers** [comment]
In fact, it's just an `elif` statement of two lines in bids.py that would make the matching during bidsoiner runtime stricter:

```python
                # Check if the attribute value matches with the info from the sourcefile
                sourcevalue = datasource.attributes(attrkey, validregexp=True)
                if attrvalue:
                    match = match and match_runvalue(sourcevalue, attrvalue)
                elif runtime:
                    match = match and sourcevalue == attrvalue
```

**Comment by marcelzwiers** [comment]
Please don't change those headers, I will make the matching stricter, let's first test that

**Comment by marcelzwiers** [comment]
I made the tiniest commit (just added: `or runtime`) that could make the biggest difference for you :-)

Can you try the letst code?

**Comment by marcelzwiers** [comment]
To come back to my analogy, I now take silence (= anonymization) as an answer instead of as a missing value

**Comment by rbonicel** [comment]
Sorry for the delay, I had to redo a bunch of steps : 
- Anonymize again some of the data, as I removed some of my folders
- Retrieve some DICOMDIR as they were corrupted along the anonymization process  (I need to be more careful with this step)
- Rerun the latest dicomsort to have the newest sorting way, along with some exams that were sorted rarely (due to their corresponding DICOMDIR organization, I think)
- Manually modify the `provenance` of the files in the bidsmap, as it was created with an old `dicomsort` version with an extra folder in the path (the `/01-/` if you remember), in order not to redo the extensive bidsmap all over again. 
- Remove all the DICOMDIR files and empty origin /DICOM folder, as the new `bidscoiner` makes a step of detecting DICOMDIR-structure (and hence giving a lot of "missing files" warning, as the `dicomsort` removes the files from the origin /DICOM folder, making the associated DICOMDIR useless)

In the end, I tried the new `bidscoiner` version, with the `runtime` bit. I still printed the `bidsmap match`, to control them.
I'm pleased to tell you that's an absolute success !! 
The matches are done properly, the coining also, and I have bids data in my bids folder !!

I still have to check the `dcm2niix` errors, mostly on dwi data, if they're legitimate. 
But with a bit of data managing, every step of the bidscoin process are now working on my data !!!

Thanks a lot for your efforts and your help. The simple `or runtime` did the trick !

**Comment by rbonicel** [comment]
I started checking the renaming of the files, to see if everything is correct. 
I have some errors on DTI data, where difference is not made between a B0 and a B1000 for instance. I see that the tag `(0018, 9087) DiffusionBValue` is not taken as `attribute`, so I guess that B0 shouldn't be labeled as `dwi` but as `fmap` or `sbref` in `dwi` type ?

These are just some adjustments to make to the bidsmap, if you could please enlighten me on this naming, before closing the issue.
Thanks again.

**Comment by marcelzwiers** [comment]
Sorry for the silence, I am currently quite occupied with fixing another
issue. The Philips Attributes may be missing in the bidsmap, because I
don't know much about them. B0 should be in dwi folder, except when it's a
reversed readout scan for computing fieldmaps, Then it should go to the
fmap folder. Doe stat answer your question? Dcm2niix should write out bval
and bvec files, I guess our b0 zero images are always saved in the same
file as the dwi images

Op do 1 feb 2024 om 17:11 schreef Robin Bonicel ***@***.***>:

**Comment by rbonicel** [comment]
No problem, I deleted my comment regarding data sorting. I thought I had it figured out using he provided guide for the study I'm currently in. 
I labeled the B0 map as sbref in the dwi folder, but I'll check with the team if I need to store them better as fmap. This was not related to this issue, and we can close it now that everything is working properly. 
Thanks again.

**Comment by marcelzwiers** [comment]
Well, I'm still worried why you got such a long list of items, or is that solved now too?

**Comment by rbonicel** [comment]
No,, it's not solved, but I'm ok wit hit. The MRI protocol was not properly set up, hence we have sequence names (and then `SeriesDesription` and `ProtocolName`) that slightly vary across scans. Then some exams went through Philips anon procedure and some don't, because they went through my lighter procedure. 
Then, I didn't shorten the TE/TR digit numbers as you suggested. 
I could check the remaining of the duplicated sequences to ename, but I'm sure it comes from there. 

A properly set up protocol with all data that undergoes the same anonymization procedure, along with truncated TE/TR would surely give me less files. But don't bother, I think the tool works great in the end.
Maybe if the possibility arises, you could someday create a Phlips template bidsmap, but with a bit of tweaking beforehand it works fine.
